[settings]
auto_install = false
lockfile = true
minimum_release_age = "3d"
pin = true

[tools]
actionlint = "1"
go = "1"
golangci-lint = "2"
pinact = "4"
shellcheck = "0.11"
zizmor = "1"

# Tasks are sorted alphabetically.
[tasks.build]
run = "go build -o sba-showroom ."
description = "Build binary"

[tasks.check]
depends = ["format:check", "lint", "test"]
description = "Run all checks"

[tasks."check:workflows"]
run = ["actionlint", "zizmor ."]
description = "Run all workflow checks"

[tasks.format]
run = "gofmt -w ."
description = "Format Go source files"

[tasks."format:check"]
run = 'test -z "$(gofmt -l .)"'
description = "Check Go source files are formatted"

[tasks.lint]
run = "golangci-lint run ./..."
description = "Lint Go source files"

[tasks."pin:actions"]
run = "pinact run --min-age 3"
description = "Pin GitHub Actions to commit SHAs"

[tasks."pin:actions:update"]
run = "pinact run --update --min-age 3"
description = "Update GitHub Actions to latest versions and pin to commit SHAs"

[tasks.test]
run = "go test ./..."
description = "Run tests"
