[settings]
auto_install = false
pin = true

[tools]
go = "1.26.4"
golangci-lint = "2.12.2"
pinact = "4.1.0"

[tasks.build]
run = "go build -o sba-showroom ."
description = "Build binary"

[tasks.check]
depends = ["fmt:check", "lint", "test"]
description = "Run all checks"

[tasks.fmt]
run = "gofmt -w ."
description = "Format Go source files"

[tasks."fmt:check"]
run = 'test -z "$(gofmt -l .)"'
description = "Check Go source files are formatted"

[tasks.lint]
run = "golangci-lint run ./..."
description = "Lint Go source files"

[tasks.test]
run = "go test ./..."
description = "Run tests"
